<?php
/**
 * MyInvestmentItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CedricZiel\OpenAPI\BondoraPHP\Model;

use \ArrayAccess;
use \CedricZiel\OpenAPI\BondoraPHP\ObjectSerializer;

/**
 * MyInvestmentItem Class Doc Comment
 *
 * @category Class
 * @description MyInvestments list item&#39;s information
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MyInvestmentItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MyInvestmentItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'loanPartId' => 'string',
        'amount' => 'double',
        'auctionId' => 'string',
        'auctionName' => 'string',
        'auctionNumber' => 'int',
        'auctionBidNumber' => 'int',
        'investmentNumber' => 'string',
        'auctionBidType' => 'int',
        'country' => 'string',
        'creditScore' => 'double',
        'creditScoreEsMicroL' => 'string',
        'creditScoreEsEquifaxRisk' => 'string',
        'creditScoreFiAsiakasTietoRiskGrade' => 'string',
        'creditScoreEeMini' => 'string',
        'rating' => 'string',
        'interest' => 'double',
        'useOfLoan' => 'int',
        'incomeVerificationStatus' => 'int',
        'loanId' => 'string',
        'loanStatusCode' => 'int',
        'loanStatusActiveFrom' => '\DateTime',
        'userName' => 'string',
        'gender' => 'int',
        'dateOfBirth' => '\DateTime',
        'signedDate' => '\DateTime',
        'reScheduledOn' => '\DateTime',
        'debtOccuredOn' => '\DateTime',
        'debtOccuredOnForSecondary' => '\DateTime',
        'loanDuration' => 'int',
        'nextPaymentNr' => 'int',
        'nextPaymentDate' => '\DateTime',
        'nextPaymentSum' => 'double',
        'nrOfScheduledPayments' => 'int',
        'lastPaymentDate' => '\DateTime',
        'principalRepaid' => 'double',
        'interestRepaid' => 'double',
        'lateAmountPaid' => 'double',
        'principalRemaining' => 'double',
        'principalLateAmount' => 'double',
        'interestLateAmount' => 'double',
        'penaltyLateAmount' => 'double',
        'lateAmountTotal' => 'double',
        'principalWriteOffAmount' => 'double',
        'interestWriteOffAmount' => 'double',
        'penaltyWriteOffAmount' => 'double',
        'debtServicingCostMainAmount' => 'double',
        'debtServicingCostInterestAmount' => 'double',
        'debtServicingCostPenaltyAmount' => 'double',
        'purchaseDate' => '\DateTime',
        'soldDate' => '\DateTime',
        'purchasePrice' => 'double',
        'salePrice' => 'double',
        'listedInSecondMarketOn' => '\DateTime',
        'latestDebtManagementStage' => 'int',
        'latestDebtManagementSubStage' => 'int',
        'latestDebtManagementStageType' => 'int',
        'latestDebtManagementDate' => '\DateTime',
        'noteLoanTransfersMainAmount' => 'double',
        'noteLoanTransfersInterestAmount' => 'double',
        'noteLoanLateChargesPaid' => 'double',
        'noteLoanTransfersEarningsAmount' => 'double',
        'noteLoanTransfersTotalRepaimentsAmount' => 'double',
        'boughtFromId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'loanPartId' => null,
        'amount' => 'double',
        'auctionId' => null,
        'auctionName' => null,
        'auctionNumber' => 'int32',
        'auctionBidNumber' => 'int32',
        'investmentNumber' => null,
        'auctionBidType' => 'int32',
        'country' => null,
        'creditScore' => 'double',
        'creditScoreEsMicroL' => null,
        'creditScoreEsEquifaxRisk' => null,
        'creditScoreFiAsiakasTietoRiskGrade' => null,
        'creditScoreEeMini' => null,
        'rating' => null,
        'interest' => 'double',
        'useOfLoan' => 'int32',
        'incomeVerificationStatus' => 'int32',
        'loanId' => null,
        'loanStatusCode' => 'int32',
        'loanStatusActiveFrom' => 'date-time',
        'userName' => null,
        'gender' => 'int32',
        'dateOfBirth' => 'date-time',
        'signedDate' => 'date-time',
        'reScheduledOn' => 'date-time',
        'debtOccuredOn' => 'date-time',
        'debtOccuredOnForSecondary' => 'date-time',
        'loanDuration' => 'int32',
        'nextPaymentNr' => 'int32',
        'nextPaymentDate' => 'date-time',
        'nextPaymentSum' => 'double',
        'nrOfScheduledPayments' => 'int32',
        'lastPaymentDate' => 'date-time',
        'principalRepaid' => 'double',
        'interestRepaid' => 'double',
        'lateAmountPaid' => 'double',
        'principalRemaining' => 'double',
        'principalLateAmount' => 'double',
        'interestLateAmount' => 'double',
        'penaltyLateAmount' => 'double',
        'lateAmountTotal' => 'double',
        'principalWriteOffAmount' => 'double',
        'interestWriteOffAmount' => 'double',
        'penaltyWriteOffAmount' => 'double',
        'debtServicingCostMainAmount' => 'double',
        'debtServicingCostInterestAmount' => 'double',
        'debtServicingCostPenaltyAmount' => 'double',
        'purchaseDate' => 'date-time',
        'soldDate' => 'date-time',
        'purchasePrice' => 'double',
        'salePrice' => 'double',
        'listedInSecondMarketOn' => 'date-time',
        'latestDebtManagementStage' => 'int32',
        'latestDebtManagementSubStage' => 'int32',
        'latestDebtManagementStageType' => 'int32',
        'latestDebtManagementDate' => 'date-time',
        'noteLoanTransfersMainAmount' => 'double',
        'noteLoanTransfersInterestAmount' => 'double',
        'noteLoanLateChargesPaid' => 'double',
        'noteLoanTransfersEarningsAmount' => 'double',
        'noteLoanTransfersTotalRepaimentsAmount' => 'double',
        'boughtFromId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'loanPartId' => 'LoanPartId',
        'amount' => 'Amount',
        'auctionId' => 'AuctionId',
        'auctionName' => 'AuctionName',
        'auctionNumber' => 'AuctionNumber',
        'auctionBidNumber' => 'AuctionBidNumber',
        'investmentNumber' => 'InvestmentNumber',
        'auctionBidType' => 'AuctionBidType',
        'country' => 'Country',
        'creditScore' => 'CreditScore',
        'creditScoreEsMicroL' => 'CreditScoreEsMicroL',
        'creditScoreEsEquifaxRisk' => 'CreditScoreEsEquifaxRisk',
        'creditScoreFiAsiakasTietoRiskGrade' => 'CreditScoreFiAsiakasTietoRiskGrade',
        'creditScoreEeMini' => 'CreditScoreEeMini',
        'rating' => 'Rating',
        'interest' => 'Interest',
        'useOfLoan' => 'UseOfLoan',
        'incomeVerificationStatus' => 'IncomeVerificationStatus',
        'loanId' => 'LoanId',
        'loanStatusCode' => 'LoanStatusCode',
        'loanStatusActiveFrom' => 'LoanStatusActiveFrom',
        'userName' => 'UserName',
        'gender' => 'Gender',
        'dateOfBirth' => 'DateOfBirth',
        'signedDate' => 'SignedDate',
        'reScheduledOn' => 'ReScheduledOn',
        'debtOccuredOn' => 'DebtOccuredOn',
        'debtOccuredOnForSecondary' => 'DebtOccuredOnForSecondary',
        'loanDuration' => 'LoanDuration',
        'nextPaymentNr' => 'NextPaymentNr',
        'nextPaymentDate' => 'NextPaymentDate',
        'nextPaymentSum' => 'NextPaymentSum',
        'nrOfScheduledPayments' => 'NrOfScheduledPayments',
        'lastPaymentDate' => 'LastPaymentDate',
        'principalRepaid' => 'PrincipalRepaid',
        'interestRepaid' => 'InterestRepaid',
        'lateAmountPaid' => 'LateAmountPaid',
        'principalRemaining' => 'PrincipalRemaining',
        'principalLateAmount' => 'PrincipalLateAmount',
        'interestLateAmount' => 'InterestLateAmount',
        'penaltyLateAmount' => 'PenaltyLateAmount',
        'lateAmountTotal' => 'LateAmountTotal',
        'principalWriteOffAmount' => 'PrincipalWriteOffAmount',
        'interestWriteOffAmount' => 'InterestWriteOffAmount',
        'penaltyWriteOffAmount' => 'PenaltyWriteOffAmount',
        'debtServicingCostMainAmount' => 'DebtServicingCostMainAmount',
        'debtServicingCostInterestAmount' => 'DebtServicingCostInterestAmount',
        'debtServicingCostPenaltyAmount' => 'DebtServicingCostPenaltyAmount',
        'purchaseDate' => 'PurchaseDate',
        'soldDate' => 'SoldDate',
        'purchasePrice' => 'PurchasePrice',
        'salePrice' => 'SalePrice',
        'listedInSecondMarketOn' => 'ListedInSecondMarketOn',
        'latestDebtManagementStage' => 'LatestDebtManagementStage',
        'latestDebtManagementSubStage' => 'LatestDebtManagementSubStage',
        'latestDebtManagementStageType' => 'LatestDebtManagementStageType',
        'latestDebtManagementDate' => 'LatestDebtManagementDate',
        'noteLoanTransfersMainAmount' => 'NoteLoanTransfersMainAmount',
        'noteLoanTransfersInterestAmount' => 'NoteLoanTransfersInterestAmount',
        'noteLoanLateChargesPaid' => 'NoteLoanLateChargesPaid',
        'noteLoanTransfersEarningsAmount' => 'NoteLoanTransfersEarningsAmount',
        'noteLoanTransfersTotalRepaimentsAmount' => 'NoteLoanTransfersTotalRepaimentsAmount',
        'boughtFromId' => 'BoughtFromId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'loanPartId' => 'setLoanPartId',
        'amount' => 'setAmount',
        'auctionId' => 'setAuctionId',
        'auctionName' => 'setAuctionName',
        'auctionNumber' => 'setAuctionNumber',
        'auctionBidNumber' => 'setAuctionBidNumber',
        'investmentNumber' => 'setInvestmentNumber',
        'auctionBidType' => 'setAuctionBidType',
        'country' => 'setCountry',
        'creditScore' => 'setCreditScore',
        'creditScoreEsMicroL' => 'setCreditScoreEsMicroL',
        'creditScoreEsEquifaxRisk' => 'setCreditScoreEsEquifaxRisk',
        'creditScoreFiAsiakasTietoRiskGrade' => 'setCreditScoreFiAsiakasTietoRiskGrade',
        'creditScoreEeMini' => 'setCreditScoreEeMini',
        'rating' => 'setRating',
        'interest' => 'setInterest',
        'useOfLoan' => 'setUseOfLoan',
        'incomeVerificationStatus' => 'setIncomeVerificationStatus',
        'loanId' => 'setLoanId',
        'loanStatusCode' => 'setLoanStatusCode',
        'loanStatusActiveFrom' => 'setLoanStatusActiveFrom',
        'userName' => 'setUserName',
        'gender' => 'setGender',
        'dateOfBirth' => 'setDateOfBirth',
        'signedDate' => 'setSignedDate',
        'reScheduledOn' => 'setReScheduledOn',
        'debtOccuredOn' => 'setDebtOccuredOn',
        'debtOccuredOnForSecondary' => 'setDebtOccuredOnForSecondary',
        'loanDuration' => 'setLoanDuration',
        'nextPaymentNr' => 'setNextPaymentNr',
        'nextPaymentDate' => 'setNextPaymentDate',
        'nextPaymentSum' => 'setNextPaymentSum',
        'nrOfScheduledPayments' => 'setNrOfScheduledPayments',
        'lastPaymentDate' => 'setLastPaymentDate',
        'principalRepaid' => 'setPrincipalRepaid',
        'interestRepaid' => 'setInterestRepaid',
        'lateAmountPaid' => 'setLateAmountPaid',
        'principalRemaining' => 'setPrincipalRemaining',
        'principalLateAmount' => 'setPrincipalLateAmount',
        'interestLateAmount' => 'setInterestLateAmount',
        'penaltyLateAmount' => 'setPenaltyLateAmount',
        'lateAmountTotal' => 'setLateAmountTotal',
        'principalWriteOffAmount' => 'setPrincipalWriteOffAmount',
        'interestWriteOffAmount' => 'setInterestWriteOffAmount',
        'penaltyWriteOffAmount' => 'setPenaltyWriteOffAmount',
        'debtServicingCostMainAmount' => 'setDebtServicingCostMainAmount',
        'debtServicingCostInterestAmount' => 'setDebtServicingCostInterestAmount',
        'debtServicingCostPenaltyAmount' => 'setDebtServicingCostPenaltyAmount',
        'purchaseDate' => 'setPurchaseDate',
        'soldDate' => 'setSoldDate',
        'purchasePrice' => 'setPurchasePrice',
        'salePrice' => 'setSalePrice',
        'listedInSecondMarketOn' => 'setListedInSecondMarketOn',
        'latestDebtManagementStage' => 'setLatestDebtManagementStage',
        'latestDebtManagementSubStage' => 'setLatestDebtManagementSubStage',
        'latestDebtManagementStageType' => 'setLatestDebtManagementStageType',
        'latestDebtManagementDate' => 'setLatestDebtManagementDate',
        'noteLoanTransfersMainAmount' => 'setNoteLoanTransfersMainAmount',
        'noteLoanTransfersInterestAmount' => 'setNoteLoanTransfersInterestAmount',
        'noteLoanLateChargesPaid' => 'setNoteLoanLateChargesPaid',
        'noteLoanTransfersEarningsAmount' => 'setNoteLoanTransfersEarningsAmount',
        'noteLoanTransfersTotalRepaimentsAmount' => 'setNoteLoanTransfersTotalRepaimentsAmount',
        'boughtFromId' => 'setBoughtFromId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'loanPartId' => 'getLoanPartId',
        'amount' => 'getAmount',
        'auctionId' => 'getAuctionId',
        'auctionName' => 'getAuctionName',
        'auctionNumber' => 'getAuctionNumber',
        'auctionBidNumber' => 'getAuctionBidNumber',
        'investmentNumber' => 'getInvestmentNumber',
        'auctionBidType' => 'getAuctionBidType',
        'country' => 'getCountry',
        'creditScore' => 'getCreditScore',
        'creditScoreEsMicroL' => 'getCreditScoreEsMicroL',
        'creditScoreEsEquifaxRisk' => 'getCreditScoreEsEquifaxRisk',
        'creditScoreFiAsiakasTietoRiskGrade' => 'getCreditScoreFiAsiakasTietoRiskGrade',
        'creditScoreEeMini' => 'getCreditScoreEeMini',
        'rating' => 'getRating',
        'interest' => 'getInterest',
        'useOfLoan' => 'getUseOfLoan',
        'incomeVerificationStatus' => 'getIncomeVerificationStatus',
        'loanId' => 'getLoanId',
        'loanStatusCode' => 'getLoanStatusCode',
        'loanStatusActiveFrom' => 'getLoanStatusActiveFrom',
        'userName' => 'getUserName',
        'gender' => 'getGender',
        'dateOfBirth' => 'getDateOfBirth',
        'signedDate' => 'getSignedDate',
        'reScheduledOn' => 'getReScheduledOn',
        'debtOccuredOn' => 'getDebtOccuredOn',
        'debtOccuredOnForSecondary' => 'getDebtOccuredOnForSecondary',
        'loanDuration' => 'getLoanDuration',
        'nextPaymentNr' => 'getNextPaymentNr',
        'nextPaymentDate' => 'getNextPaymentDate',
        'nextPaymentSum' => 'getNextPaymentSum',
        'nrOfScheduledPayments' => 'getNrOfScheduledPayments',
        'lastPaymentDate' => 'getLastPaymentDate',
        'principalRepaid' => 'getPrincipalRepaid',
        'interestRepaid' => 'getInterestRepaid',
        'lateAmountPaid' => 'getLateAmountPaid',
        'principalRemaining' => 'getPrincipalRemaining',
        'principalLateAmount' => 'getPrincipalLateAmount',
        'interestLateAmount' => 'getInterestLateAmount',
        'penaltyLateAmount' => 'getPenaltyLateAmount',
        'lateAmountTotal' => 'getLateAmountTotal',
        'principalWriteOffAmount' => 'getPrincipalWriteOffAmount',
        'interestWriteOffAmount' => 'getInterestWriteOffAmount',
        'penaltyWriteOffAmount' => 'getPenaltyWriteOffAmount',
        'debtServicingCostMainAmount' => 'getDebtServicingCostMainAmount',
        'debtServicingCostInterestAmount' => 'getDebtServicingCostInterestAmount',
        'debtServicingCostPenaltyAmount' => 'getDebtServicingCostPenaltyAmount',
        'purchaseDate' => 'getPurchaseDate',
        'soldDate' => 'getSoldDate',
        'purchasePrice' => 'getPurchasePrice',
        'salePrice' => 'getSalePrice',
        'listedInSecondMarketOn' => 'getListedInSecondMarketOn',
        'latestDebtManagementStage' => 'getLatestDebtManagementStage',
        'latestDebtManagementSubStage' => 'getLatestDebtManagementSubStage',
        'latestDebtManagementStageType' => 'getLatestDebtManagementStageType',
        'latestDebtManagementDate' => 'getLatestDebtManagementDate',
        'noteLoanTransfersMainAmount' => 'getNoteLoanTransfersMainAmount',
        'noteLoanTransfersInterestAmount' => 'getNoteLoanTransfersInterestAmount',
        'noteLoanLateChargesPaid' => 'getNoteLoanLateChargesPaid',
        'noteLoanTransfersEarningsAmount' => 'getNoteLoanTransfersEarningsAmount',
        'noteLoanTransfersTotalRepaimentsAmount' => 'getNoteLoanTransfersTotalRepaimentsAmount',
        'boughtFromId' => 'getBoughtFromId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const AUCTION_BID_TYPE_0 = 0;
    const AUCTION_BID_TYPE_1 = 1;
    const AUCTION_BID_TYPE_2 = 2;
    const AUCTION_BID_TYPE_3 = 3;
    const USE_OF_LOAN_0 = 0;
    const USE_OF_LOAN_1 = 1;
    const USE_OF_LOAN_2 = 2;
    const USE_OF_LOAN_3 = 3;
    const USE_OF_LOAN_4 = 4;
    const USE_OF_LOAN_5 = 5;
    const USE_OF_LOAN_6 = 6;
    const USE_OF_LOAN_7 = 7;
    const USE_OF_LOAN_8 = 8;
    const USE_OF_LOAN_101 = 101;
    const USE_OF_LOAN_102 = 102;
    const USE_OF_LOAN_103 = 103;
    const USE_OF_LOAN_104 = 104;
    const USE_OF_LOAN_105 = 105;
    const USE_OF_LOAN_106 = 106;
    const USE_OF_LOAN_107 = 107;
    const USE_OF_LOAN_108 = 108;
    const USE_OF_LOAN_109 = 109;
    const USE_OF_LOAN_110 = 110;
    const USE_OF_LOAN_201 = 201;
    const USE_OF_LOAN_202 = 202;
    const USE_OF_LOAN_203 = 203;
    const USE_OF_LOAN_204 = 204;
    const USE_OF_LOAN_205 = 205;
    const USE_OF_LOAN_206 = 206;
    const USE_OF_LOAN_207 = 207;
    const USE_OF_LOAN_208 = 208;
    const USE_OF_LOAN_209 = 209;
    const USE_OF_LOAN_210 = 210;
    const USE_OF_LOAN_211 = 211;
    const USE_OF_LOAN_MINUS_1 = -1;
    const INCOME_VERIFICATION_STATUS_1 = 1;
    const INCOME_VERIFICATION_STATUS_2 = 2;
    const INCOME_VERIFICATION_STATUS_3 = 3;
    const INCOME_VERIFICATION_STATUS_4 = 4;
    const GENDER_0 = 0;
    const GENDER_1 = 1;
    const GENDER_2 = 2;
    const LATEST_DEBT_MANAGEMENT_STAGE_1 = 1;
    const LATEST_DEBT_MANAGEMENT_STAGE_2 = 2;
    const LATEST_DEBT_MANAGEMENT_STAGE_7 = 7;
    const LATEST_DEBT_MANAGEMENT_STAGE_9 = 9;
    const LATEST_DEBT_MANAGEMENT_STAGE_14 = 14;
    const LATEST_DEBT_MANAGEMENT_STAGE_15 = 15;
    const LATEST_DEBT_MANAGEMENT_STAGE_16 = 16;
    const LATEST_DEBT_MANAGEMENT_STAGE_20 = 20;
    const LATEST_DEBT_MANAGEMENT_STAGE_22 = 22;
    const LATEST_DEBT_MANAGEMENT_STAGE_23 = 23;
    const LATEST_DEBT_MANAGEMENT_STAGE_24 = 24;
    const LATEST_DEBT_MANAGEMENT_STAGE_30 = 30;
    const LATEST_DEBT_MANAGEMENT_STAGE_31 = 31;
    const LATEST_DEBT_MANAGEMENT_STAGE_32 = 32;
    const LATEST_DEBT_MANAGEMENT_STAGE_33 = 33;
    const LATEST_DEBT_MANAGEMENT_STAGE_34 = 34;
    const LATEST_DEBT_MANAGEMENT_STAGE_35 = 35;
    const LATEST_DEBT_MANAGEMENT_STAGE_36 = 36;
    const LATEST_DEBT_MANAGEMENT_STAGE_37 = 37;
    const LATEST_DEBT_MANAGEMENT_STAGE_38 = 38;
    const LATEST_DEBT_MANAGEMENT_STAGE_39 = 39;
    const LATEST_DEBT_MANAGEMENT_STAGE_40 = 40;
    const LATEST_DEBT_MANAGEMENT_STAGE_41 = 41;
    const LATEST_DEBT_MANAGEMENT_STAGE_42 = 42;
    const LATEST_DEBT_MANAGEMENT_STAGE_43 = 43;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_1 = 1;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_2 = 2;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_3 = 3;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_4 = 4;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_5 = 5;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_6 = 6;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_7 = 7;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_8 = 8;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_9 = 9;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_10 = 10;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_11 = 11;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_12 = 12;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_13 = 13;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_14 = 14;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_15 = 15;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_16 = 16;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_17 = 17;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_18 = 18;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_19 = 19;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_20 = 20;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_21 = 21;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_22 = 22;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_23 = 23;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_24 = 24;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_25 = 25;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_26 = 26;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_27 = 27;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_28 = 28;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_29 = 29;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_30 = 30;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_31 = 31;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_32 = 32;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_33 = 33;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_36 = 36;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_38 = 38;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_39 = 39;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_40 = 40;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_41 = 41;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_42 = 42;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_43 = 43;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_44 = 44;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_45 = 45;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_46 = 46;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_47 = 47;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_48 = 48;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_49 = 49;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_50 = 50;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_51 = 51;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_52 = 52;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_53 = 53;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_54 = 54;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_55 = 55;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_56 = 56;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_57 = 57;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_58 = 58;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_59 = 59;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_60 = 60;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_61 = 61;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_62 = 62;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_63 = 63;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_64 = 64;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_65 = 65;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_66 = 66;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_67 = 67;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_68 = 68;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_69 = 69;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_70 = 70;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_71 = 71;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_72 = 72;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_73 = 73;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_74 = 74;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_75 = 75;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_76 = 76;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_77 = 77;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_78 = 78;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_79 = 79;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_80 = 80;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_81 = 81;
    const LATEST_DEBT_MANAGEMENT_SUB_STAGE_82 = 82;
    const LATEST_DEBT_MANAGEMENT_STAGE_TYPE_1 = 1;
    const LATEST_DEBT_MANAGEMENT_STAGE_TYPE_2 = 2;
    const LATEST_DEBT_MANAGEMENT_STAGE_TYPE_3 = 3;
    const LATEST_DEBT_MANAGEMENT_STAGE_TYPE_MINUS_1 = -1;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuctionBidTypeAllowableValues()
    {
        return [
            self::AUCTION_BID_TYPE_0,
            self::AUCTION_BID_TYPE_1,
            self::AUCTION_BID_TYPE_2,
            self::AUCTION_BID_TYPE_3,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUseOfLoanAllowableValues()
    {
        return [
            self::USE_OF_LOAN_0,
            self::USE_OF_LOAN_1,
            self::USE_OF_LOAN_2,
            self::USE_OF_LOAN_3,
            self::USE_OF_LOAN_4,
            self::USE_OF_LOAN_5,
            self::USE_OF_LOAN_6,
            self::USE_OF_LOAN_7,
            self::USE_OF_LOAN_8,
            self::USE_OF_LOAN_101,
            self::USE_OF_LOAN_102,
            self::USE_OF_LOAN_103,
            self::USE_OF_LOAN_104,
            self::USE_OF_LOAN_105,
            self::USE_OF_LOAN_106,
            self::USE_OF_LOAN_107,
            self::USE_OF_LOAN_108,
            self::USE_OF_LOAN_109,
            self::USE_OF_LOAN_110,
            self::USE_OF_LOAN_201,
            self::USE_OF_LOAN_202,
            self::USE_OF_LOAN_203,
            self::USE_OF_LOAN_204,
            self::USE_OF_LOAN_205,
            self::USE_OF_LOAN_206,
            self::USE_OF_LOAN_207,
            self::USE_OF_LOAN_208,
            self::USE_OF_LOAN_209,
            self::USE_OF_LOAN_210,
            self::USE_OF_LOAN_211,
            self::USE_OF_LOAN_MINUS_1,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIncomeVerificationStatusAllowableValues()
    {
        return [
            self::INCOME_VERIFICATION_STATUS_1,
            self::INCOME_VERIFICATION_STATUS_2,
            self::INCOME_VERIFICATION_STATUS_3,
            self::INCOME_VERIFICATION_STATUS_4,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderAllowableValues()
    {
        return [
            self::GENDER_0,
            self::GENDER_1,
            self::GENDER_2,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLatestDebtManagementStageAllowableValues()
    {
        return [
            self::LATEST_DEBT_MANAGEMENT_STAGE_1,
            self::LATEST_DEBT_MANAGEMENT_STAGE_2,
            self::LATEST_DEBT_MANAGEMENT_STAGE_7,
            self::LATEST_DEBT_MANAGEMENT_STAGE_9,
            self::LATEST_DEBT_MANAGEMENT_STAGE_14,
            self::LATEST_DEBT_MANAGEMENT_STAGE_15,
            self::LATEST_DEBT_MANAGEMENT_STAGE_16,
            self::LATEST_DEBT_MANAGEMENT_STAGE_20,
            self::LATEST_DEBT_MANAGEMENT_STAGE_22,
            self::LATEST_DEBT_MANAGEMENT_STAGE_23,
            self::LATEST_DEBT_MANAGEMENT_STAGE_24,
            self::LATEST_DEBT_MANAGEMENT_STAGE_30,
            self::LATEST_DEBT_MANAGEMENT_STAGE_31,
            self::LATEST_DEBT_MANAGEMENT_STAGE_32,
            self::LATEST_DEBT_MANAGEMENT_STAGE_33,
            self::LATEST_DEBT_MANAGEMENT_STAGE_34,
            self::LATEST_DEBT_MANAGEMENT_STAGE_35,
            self::LATEST_DEBT_MANAGEMENT_STAGE_36,
            self::LATEST_DEBT_MANAGEMENT_STAGE_37,
            self::LATEST_DEBT_MANAGEMENT_STAGE_38,
            self::LATEST_DEBT_MANAGEMENT_STAGE_39,
            self::LATEST_DEBT_MANAGEMENT_STAGE_40,
            self::LATEST_DEBT_MANAGEMENT_STAGE_41,
            self::LATEST_DEBT_MANAGEMENT_STAGE_42,
            self::LATEST_DEBT_MANAGEMENT_STAGE_43,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLatestDebtManagementSubStageAllowableValues()
    {
        return [
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_1,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_2,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_3,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_4,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_5,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_6,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_7,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_8,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_9,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_10,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_11,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_12,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_13,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_14,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_15,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_16,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_17,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_18,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_19,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_20,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_21,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_22,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_23,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_24,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_25,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_26,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_27,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_28,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_29,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_30,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_31,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_32,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_33,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_36,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_38,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_39,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_40,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_41,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_42,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_43,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_44,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_45,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_46,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_47,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_48,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_49,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_50,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_51,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_52,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_53,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_54,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_55,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_56,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_57,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_58,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_59,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_60,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_61,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_62,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_63,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_64,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_65,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_66,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_67,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_68,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_69,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_70,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_71,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_72,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_73,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_74,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_75,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_76,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_77,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_78,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_79,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_80,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_81,
            self::LATEST_DEBT_MANAGEMENT_SUB_STAGE_82,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLatestDebtManagementStageTypeAllowableValues()
    {
        return [
            self::LATEST_DEBT_MANAGEMENT_STAGE_TYPE_1,
            self::LATEST_DEBT_MANAGEMENT_STAGE_TYPE_2,
            self::LATEST_DEBT_MANAGEMENT_STAGE_TYPE_3,
            self::LATEST_DEBT_MANAGEMENT_STAGE_TYPE_MINUS_1,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['loanPartId'] = isset($data['loanPartId']) ? $data['loanPartId'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['auctionId'] = isset($data['auctionId']) ? $data['auctionId'] : null;
        $this->container['auctionName'] = isset($data['auctionName']) ? $data['auctionName'] : null;
        $this->container['auctionNumber'] = isset($data['auctionNumber']) ? $data['auctionNumber'] : null;
        $this->container['auctionBidNumber'] = isset($data['auctionBidNumber']) ? $data['auctionBidNumber'] : null;
        $this->container['investmentNumber'] = isset($data['investmentNumber']) ? $data['investmentNumber'] : null;
        $this->container['auctionBidType'] = isset($data['auctionBidType']) ? $data['auctionBidType'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['creditScore'] = isset($data['creditScore']) ? $data['creditScore'] : null;
        $this->container['creditScoreEsMicroL'] = isset($data['creditScoreEsMicroL']) ? $data['creditScoreEsMicroL'] : null;
        $this->container['creditScoreEsEquifaxRisk'] = isset($data['creditScoreEsEquifaxRisk']) ? $data['creditScoreEsEquifaxRisk'] : null;
        $this->container['creditScoreFiAsiakasTietoRiskGrade'] = isset($data['creditScoreFiAsiakasTietoRiskGrade']) ? $data['creditScoreFiAsiakasTietoRiskGrade'] : null;
        $this->container['creditScoreEeMini'] = isset($data['creditScoreEeMini']) ? $data['creditScoreEeMini'] : null;
        $this->container['rating'] = isset($data['rating']) ? $data['rating'] : null;
        $this->container['interest'] = isset($data['interest']) ? $data['interest'] : null;
        $this->container['useOfLoan'] = isset($data['useOfLoan']) ? $data['useOfLoan'] : null;
        $this->container['incomeVerificationStatus'] = isset($data['incomeVerificationStatus']) ? $data['incomeVerificationStatus'] : null;
        $this->container['loanId'] = isset($data['loanId']) ? $data['loanId'] : null;
        $this->container['loanStatusCode'] = isset($data['loanStatusCode']) ? $data['loanStatusCode'] : null;
        $this->container['loanStatusActiveFrom'] = isset($data['loanStatusActiveFrom']) ? $data['loanStatusActiveFrom'] : null;
        $this->container['userName'] = isset($data['userName']) ? $data['userName'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['dateOfBirth'] = isset($data['dateOfBirth']) ? $data['dateOfBirth'] : null;
        $this->container['signedDate'] = isset($data['signedDate']) ? $data['signedDate'] : null;
        $this->container['reScheduledOn'] = isset($data['reScheduledOn']) ? $data['reScheduledOn'] : null;
        $this->container['debtOccuredOn'] = isset($data['debtOccuredOn']) ? $data['debtOccuredOn'] : null;
        $this->container['debtOccuredOnForSecondary'] = isset($data['debtOccuredOnForSecondary']) ? $data['debtOccuredOnForSecondary'] : null;
        $this->container['loanDuration'] = isset($data['loanDuration']) ? $data['loanDuration'] : null;
        $this->container['nextPaymentNr'] = isset($data['nextPaymentNr']) ? $data['nextPaymentNr'] : null;
        $this->container['nextPaymentDate'] = isset($data['nextPaymentDate']) ? $data['nextPaymentDate'] : null;
        $this->container['nextPaymentSum'] = isset($data['nextPaymentSum']) ? $data['nextPaymentSum'] : null;
        $this->container['nrOfScheduledPayments'] = isset($data['nrOfScheduledPayments']) ? $data['nrOfScheduledPayments'] : null;
        $this->container['lastPaymentDate'] = isset($data['lastPaymentDate']) ? $data['lastPaymentDate'] : null;
        $this->container['principalRepaid'] = isset($data['principalRepaid']) ? $data['principalRepaid'] : null;
        $this->container['interestRepaid'] = isset($data['interestRepaid']) ? $data['interestRepaid'] : null;
        $this->container['lateAmountPaid'] = isset($data['lateAmountPaid']) ? $data['lateAmountPaid'] : null;
        $this->container['principalRemaining'] = isset($data['principalRemaining']) ? $data['principalRemaining'] : null;
        $this->container['principalLateAmount'] = isset($data['principalLateAmount']) ? $data['principalLateAmount'] : null;
        $this->container['interestLateAmount'] = isset($data['interestLateAmount']) ? $data['interestLateAmount'] : null;
        $this->container['penaltyLateAmount'] = isset($data['penaltyLateAmount']) ? $data['penaltyLateAmount'] : null;
        $this->container['lateAmountTotal'] = isset($data['lateAmountTotal']) ? $data['lateAmountTotal'] : null;
        $this->container['principalWriteOffAmount'] = isset($data['principalWriteOffAmount']) ? $data['principalWriteOffAmount'] : null;
        $this->container['interestWriteOffAmount'] = isset($data['interestWriteOffAmount']) ? $data['interestWriteOffAmount'] : null;
        $this->container['penaltyWriteOffAmount'] = isset($data['penaltyWriteOffAmount']) ? $data['penaltyWriteOffAmount'] : null;
        $this->container['debtServicingCostMainAmount'] = isset($data['debtServicingCostMainAmount']) ? $data['debtServicingCostMainAmount'] : null;
        $this->container['debtServicingCostInterestAmount'] = isset($data['debtServicingCostInterestAmount']) ? $data['debtServicingCostInterestAmount'] : null;
        $this->container['debtServicingCostPenaltyAmount'] = isset($data['debtServicingCostPenaltyAmount']) ? $data['debtServicingCostPenaltyAmount'] : null;
        $this->container['purchaseDate'] = isset($data['purchaseDate']) ? $data['purchaseDate'] : null;
        $this->container['soldDate'] = isset($data['soldDate']) ? $data['soldDate'] : null;
        $this->container['purchasePrice'] = isset($data['purchasePrice']) ? $data['purchasePrice'] : null;
        $this->container['salePrice'] = isset($data['salePrice']) ? $data['salePrice'] : null;
        $this->container['listedInSecondMarketOn'] = isset($data['listedInSecondMarketOn']) ? $data['listedInSecondMarketOn'] : null;
        $this->container['latestDebtManagementStage'] = isset($data['latestDebtManagementStage']) ? $data['latestDebtManagementStage'] : null;
        $this->container['latestDebtManagementSubStage'] = isset($data['latestDebtManagementSubStage']) ? $data['latestDebtManagementSubStage'] : null;
        $this->container['latestDebtManagementStageType'] = isset($data['latestDebtManagementStageType']) ? $data['latestDebtManagementStageType'] : null;
        $this->container['latestDebtManagementDate'] = isset($data['latestDebtManagementDate']) ? $data['latestDebtManagementDate'] : null;
        $this->container['noteLoanTransfersMainAmount'] = isset($data['noteLoanTransfersMainAmount']) ? $data['noteLoanTransfersMainAmount'] : null;
        $this->container['noteLoanTransfersInterestAmount'] = isset($data['noteLoanTransfersInterestAmount']) ? $data['noteLoanTransfersInterestAmount'] : null;
        $this->container['noteLoanLateChargesPaid'] = isset($data['noteLoanLateChargesPaid']) ? $data['noteLoanLateChargesPaid'] : null;
        $this->container['noteLoanTransfersEarningsAmount'] = isset($data['noteLoanTransfersEarningsAmount']) ? $data['noteLoanTransfersEarningsAmount'] : null;
        $this->container['noteLoanTransfersTotalRepaimentsAmount'] = isset($data['noteLoanTransfersTotalRepaimentsAmount']) ? $data['noteLoanTransfersTotalRepaimentsAmount'] : null;
        $this->container['boughtFromId'] = isset($data['boughtFromId']) ? $data['boughtFromId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAuctionBidTypeAllowableValues();
        if (!is_null($this->container['auctionBidType']) && !in_array($this->container['auctionBidType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'auctionBidType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getUseOfLoanAllowableValues();
        if (!is_null($this->container['useOfLoan']) && !in_array($this->container['useOfLoan'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'useOfLoan', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIncomeVerificationStatusAllowableValues();
        if (!is_null($this->container['incomeVerificationStatus']) && !in_array($this->container['incomeVerificationStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'incomeVerificationStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($this->container['gender']) && !in_array($this->container['gender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'gender', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLatestDebtManagementStageAllowableValues();
        if (!is_null($this->container['latestDebtManagementStage']) && !in_array($this->container['latestDebtManagementStage'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'latestDebtManagementStage', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLatestDebtManagementSubStageAllowableValues();
        if (!is_null($this->container['latestDebtManagementSubStage']) && !in_array($this->container['latestDebtManagementSubStage'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'latestDebtManagementSubStage', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLatestDebtManagementStageTypeAllowableValues();
        if (!is_null($this->container['latestDebtManagementStageType']) && !in_array($this->container['latestDebtManagementStageType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'latestDebtManagementStageType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets loanPartId
     *
     * @return string|null
     */
    public function getLoanPartId()
    {
        return $this->container['loanPartId'];
    }

    /**
     * Sets loanPartId
     *
     * @param string|null $loanPartId LoanPart unique identifier
     *
     * @return $this
     */
    public function setLoanPartId($loanPartId)
    {
        $this->container['loanPartId'] = $loanPartId;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return double|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param double|null $amount Investment amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets auctionId
     *
     * @return string|null
     */
    public function getAuctionId()
    {
        return $this->container['auctionId'];
    }

    /**
     * Sets auctionId
     *
     * @param string|null $auctionId Auction unique identifier
     *
     * @return $this
     */
    public function setAuctionId($auctionId)
    {
        $this->container['auctionId'] = $auctionId;

        return $this;
    }

    /**
     * Gets auctionName
     *
     * @return string|null
     */
    public function getAuctionName()
    {
        return $this->container['auctionName'];
    }

    /**
     * Sets auctionName
     *
     * @param string|null $auctionName Auction name
     *
     * @return $this
     */
    public function setAuctionName($auctionName)
    {
        $this->container['auctionName'] = $auctionName;

        return $this;
    }

    /**
     * Gets auctionNumber
     *
     * @return int|null
     */
    public function getAuctionNumber()
    {
        return $this->container['auctionNumber'];
    }

    /**
     * Sets auctionNumber
     *
     * @param int|null $auctionNumber Auction number
     *
     * @return $this
     */
    public function setAuctionNumber($auctionNumber)
    {
        $this->container['auctionNumber'] = $auctionNumber;

        return $this;
    }

    /**
     * Gets auctionBidNumber
     *
     * @return int|null
     */
    public function getAuctionBidNumber()
    {
        return $this->container['auctionBidNumber'];
    }

    /**
     * Sets auctionBidNumber
     *
     * @param int|null $auctionBidNumber Auction bid number
     *
     * @return $this
     */
    public function setAuctionBidNumber($auctionBidNumber)
    {
        $this->container['auctionBidNumber'] = $auctionBidNumber;

        return $this;
    }

    /**
     * Gets investmentNumber
     *
     * @return string|null
     */
    public function getInvestmentNumber()
    {
        return $this->container['investmentNumber'];
    }

    /**
     * Sets investmentNumber
     *
     * @param string|null $investmentNumber investmentNumber
     *
     * @return $this
     */
    public function setInvestmentNumber($investmentNumber)
    {
        $this->container['investmentNumber'] = $investmentNumber;

        return $this;
    }

    /**
     * Gets auctionBidType
     *
     * @return int|null
     */
    public function getAuctionBidType()
    {
        return $this->container['auctionBidType'];
    }

    /**
     * Sets auctionBidType
     *
     * @param int|null $auctionBidType Auction bid type
     *
     * @return $this
     */
    public function setAuctionBidType($auctionBidType)
    {
        $allowedValues = $this->getAuctionBidTypeAllowableValues();
        if (!is_null($auctionBidType) && !in_array($auctionBidType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'auctionBidType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auctionBidType'] = $auctionBidType;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country Residency of the borrower
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets creditScore
     *
     * @return double|null
     */
    public function getCreditScore()
    {
        return $this->container['creditScore'];
    }

    /**
     * Sets creditScore
     *
     * @param double|null $creditScore <para>    1000 No previous payments problems</para>  <para>    900 Payments problems finished 24-36 months ago</para>  <para>    800 Payments problems finished 12-24 months ago</para>  <para>    700 Payments problems finished 6-12 months ago</para>  <para>    600 Payment problems finished &lt;6 months ago</para>  <para>    500 Active payment problems</para>
     *
     * @return $this
     */
    public function setCreditScore($creditScore)
    {
        $this->container['creditScore'] = $creditScore;

        return $this;
    }

    /**
     * Gets creditScoreEsMicroL
     *
     * @return string|null
     */
    public function getCreditScoreEsMicroL()
    {
        return $this->container['creditScoreEsMicroL'];
    }

    /**
     * Sets creditScoreEsMicroL
     *
     * @param string|null $creditScoreEsMicroL A score that is specifically designed for risk classifying subprime borrowers (defined by Equifax as borrowers that do not have access to bank loans).               A measure of the probability of default one month ahead.              <para>The score is given on a 10-grade scale, from the best score to the worst:</para><para>M1, M2, M3, M4, M5, M6, M7, M8, M9, M10</para>
     *
     * @return $this
     */
    public function setCreditScoreEsMicroL($creditScoreEsMicroL)
    {
        $this->container['creditScoreEsMicroL'] = $creditScoreEsMicroL;

        return $this;
    }

    /**
     * Gets creditScoreEsEquifaxRisk
     *
     * @return string|null
     */
    public function getCreditScoreEsEquifaxRisk()
    {
        return $this->container['creditScoreEsEquifaxRisk'];
    }

    /**
     * Sets creditScoreEsEquifaxRisk
     *
     * @param string|null $creditScoreEsEquifaxRisk Generic score for the loan applicants that do not have active past due operations in ASNEF.              A measure of the probability of default one year ahead.               The score is given on a 6-grade scale.              <para>AAA Very low</para><para>AA Low</para><para>A Average</para><para>B Average High</para><para>C High</para><para>D Very High</para>
     *
     * @return $this
     */
    public function setCreditScoreEsEquifaxRisk($creditScoreEsEquifaxRisk)
    {
        $this->container['creditScoreEsEquifaxRisk'] = $creditScoreEsEquifaxRisk;

        return $this;
    }

    /**
     * Gets creditScoreFiAsiakasTietoRiskGrade
     *
     * @return string|null
     */
    public function getCreditScoreFiAsiakasTietoRiskGrade()
    {
        return $this->container['creditScoreFiAsiakasTietoRiskGrade'];
    }

    /**
     * Sets creditScoreFiAsiakasTietoRiskGrade
     *
     * @param string|null $creditScoreFiAsiakasTietoRiskGrade Credit Scoring model for Finnish Asiakastieto              <para>RL1 Very low risk 01-20</para><para>RL2 Low risk 21-40</para><para>RL3 Average risk 41-60</para><para>RL4 Big risk 61-80</para><para>RL5 Huge risk 81-100</para>
     *
     * @return $this
     */
    public function setCreditScoreFiAsiakasTietoRiskGrade($creditScoreFiAsiakasTietoRiskGrade)
    {
        $this->container['creditScoreFiAsiakasTietoRiskGrade'] = $creditScoreFiAsiakasTietoRiskGrade;

        return $this;
    }

    /**
     * Gets creditScoreEeMini
     *
     * @return string|null
     */
    public function getCreditScoreEeMini()
    {
        return $this->container['creditScoreEeMini'];
    }

    /**
     * Sets creditScoreEeMini
     *
     * @param string|null $creditScoreEeMini Credit scoring for Estonian loans              <para>1000 No previous payments problems</para><para>900 Payments problems finished 24-36 months ago</para><para>800 Payments problems finished 12-24 months ago</para><para>700 Payments problems finished 6-12 months ago</para><para>600 Payment problems finished &lt;6 months ago</para><para>500 Active payment problems</para>
     *
     * @return $this
     */
    public function setCreditScoreEeMini($creditScoreEeMini)
    {
        $this->container['creditScoreEeMini'] = $creditScoreEeMini;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return string|null
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param string|null $rating Bondora Rating issued by the Rating model
     *
     * @return $this
     */
    public function setRating($rating)
    {
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets interest
     *
     * @return double|null
     */
    public function getInterest()
    {
        return $this->container['interest'];
    }

    /**
     * Sets interest
     *
     * @param double|null $interest Interest rate
     *
     * @return $this
     */
    public function setInterest($interest)
    {
        $this->container['interest'] = $interest;

        return $this;
    }

    /**
     * Gets useOfLoan
     *
     * @return int|null
     */
    public function getUseOfLoan()
    {
        return $this->container['useOfLoan'];
    }

    /**
     * Sets useOfLoan
     *
     * @param int|null $useOfLoan Use of loan
     *
     * @return $this
     */
    public function setUseOfLoan($useOfLoan)
    {
        $allowedValues = $this->getUseOfLoanAllowableValues();
        if (!is_null($useOfLoan) && !in_array($useOfLoan, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'useOfLoan', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['useOfLoan'] = $useOfLoan;

        return $this;
    }

    /**
     * Gets incomeVerificationStatus
     *
     * @return int|null
     */
    public function getIncomeVerificationStatus()
    {
        return $this->container['incomeVerificationStatus'];
    }

    /**
     * Sets incomeVerificationStatus
     *
     * @param int|null $incomeVerificationStatus Income verification type
     *
     * @return $this
     */
    public function setIncomeVerificationStatus($incomeVerificationStatus)
    {
        $allowedValues = $this->getIncomeVerificationStatusAllowableValues();
        if (!is_null($incomeVerificationStatus) && !in_array($incomeVerificationStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'incomeVerificationStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['incomeVerificationStatus'] = $incomeVerificationStatus;

        return $this;
    }

    /**
     * Gets loanId
     *
     * @return string|null
     */
    public function getLoanId()
    {
        return $this->container['loanId'];
    }

    /**
     * Sets loanId
     *
     * @param string|null $loanId Loan unique identifier
     *
     * @return $this
     */
    public function setLoanId($loanId)
    {
        $this->container['loanId'] = $loanId;

        return $this;
    }

    /**
     * Gets loanStatusCode
     *
     * @return int|null
     */
    public function getLoanStatusCode()
    {
        return $this->container['loanStatusCode'];
    }

    /**
     * Sets loanStatusCode
     *
     * @param int|null $loanStatusCode Loan status code              <para>0 Reserved</para><para>2 Current</para><para>3 Cancelled</para><para>100 Overdue</para><para>5 60+ days overdue</para><para>4 Repaid</para><para>8 Released</para>
     *
     * @return $this
     */
    public function setLoanStatusCode($loanStatusCode)
    {
        $this->container['loanStatusCode'] = $loanStatusCode;

        return $this;
    }

    /**
     * Gets loanStatusActiveFrom
     *
     * @return \DateTime|null
     */
    public function getLoanStatusActiveFrom()
    {
        return $this->container['loanStatusActiveFrom'];
    }

    /**
     * Sets loanStatusActiveFrom
     *
     * @param \DateTime|null $loanStatusActiveFrom Loan status active from
     *
     * @return $this
     */
    public function setLoanStatusActiveFrom($loanStatusActiveFrom)
    {
        $this->container['loanStatusActiveFrom'] = $loanStatusActiveFrom;

        return $this;
    }

    /**
     * Gets userName
     *
     * @return string|null
     */
    public function getUserName()
    {
        return $this->container['userName'];
    }

    /**
     * Sets userName
     *
     * @param string|null $userName Borrower's username
     *
     * @return $this
     */
    public function setUserName($userName)
    {
        $this->container['userName'] = $userName;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return int|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param int|null $gender Borrower's Gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($gender) && !in_array($gender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'gender', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets dateOfBirth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth()
    {
        return $this->container['dateOfBirth'];
    }

    /**
     * Sets dateOfBirth
     *
     * @param \DateTime|null $dateOfBirth Borrower's date of birth
     *
     * @return $this
     */
    public function setDateOfBirth($dateOfBirth)
    {
        $this->container['dateOfBirth'] = $dateOfBirth;

        return $this;
    }

    /**
     * Gets signedDate
     *
     * @return \DateTime|null
     */
    public function getSignedDate()
    {
        return $this->container['signedDate'];
    }

    /**
     * Sets signedDate
     *
     * @param \DateTime|null $signedDate Loan issued date
     *
     * @return $this
     */
    public function setSignedDate($signedDate)
    {
        $this->container['signedDate'] = $signedDate;

        return $this;
    }

    /**
     * Gets reScheduledOn
     *
     * @return \DateTime|null
     */
    public function getReScheduledOn()
    {
        return $this->container['reScheduledOn'];
    }

    /**
     * Sets reScheduledOn
     *
     * @param \DateTime|null $reScheduledOn Last rescheduling date
     *
     * @return $this
     */
    public function setReScheduledOn($reScheduledOn)
    {
        $this->container['reScheduledOn'] = $reScheduledOn;

        return $this;
    }

    /**
     * Gets debtOccuredOn
     *
     * @return \DateTime|null
     */
    public function getDebtOccuredOn()
    {
        return $this->container['debtOccuredOn'];
    }

    /**
     * Sets debtOccuredOn
     *
     * @param \DateTime|null $debtOccuredOn Date and time when the principal part of the payment is overdue (PrincipalLateAmount is greater than zero).
     *
     * @return $this
     */
    public function setDebtOccuredOn($debtOccuredOn)
    {
        $this->container['debtOccuredOn'] = $debtOccuredOn;

        return $this;
    }

    /**
     * Gets debtOccuredOnForSecondary
     *
     * @return \DateTime|null
     */
    public function getDebtOccuredOnForSecondary()
    {
        return $this->container['debtOccuredOnForSecondary'];
    }

    /**
     * Sets debtOccuredOnForSecondary
     *
     * @param \DateTime|null $debtOccuredOnForSecondary Date and time when loan part payment is overdue (principal, interest or penalty) aka when the dept occured for the loan part (LateAmountTotal is greater than zero).
     *
     * @return $this
     */
    public function setDebtOccuredOnForSecondary($debtOccuredOnForSecondary)
    {
        $this->container['debtOccuredOnForSecondary'] = $debtOccuredOnForSecondary;

        return $this;
    }

    /**
     * Gets loanDuration
     *
     * @return int|null
     */
    public function getLoanDuration()
    {
        return $this->container['loanDuration'];
    }

    /**
     * Sets loanDuration
     *
     * @param int|null $loanDuration Loan original lenght
     *
     * @return $this
     */
    public function setLoanDuration($loanDuration)
    {
        $this->container['loanDuration'] = $loanDuration;

        return $this;
    }

    /**
     * Gets nextPaymentNr
     *
     * @return int|null
     */
    public function getNextPaymentNr()
    {
        return $this->container['nextPaymentNr'];
    }

    /**
     * Sets nextPaymentNr
     *
     * @param int|null $nextPaymentNr Next scheduled payment number
     *
     * @return $this
     */
    public function setNextPaymentNr($nextPaymentNr)
    {
        $this->container['nextPaymentNr'] = $nextPaymentNr;

        return $this;
    }

    /**
     * Gets nextPaymentDate
     *
     * @return \DateTime|null
     */
    public function getNextPaymentDate()
    {
        return $this->container['nextPaymentDate'];
    }

    /**
     * Sets nextPaymentDate
     *
     * @param \DateTime|null $nextPaymentDate Next scheduled payment date
     *
     * @return $this
     */
    public function setNextPaymentDate($nextPaymentDate)
    {
        $this->container['nextPaymentDate'] = $nextPaymentDate;

        return $this;
    }

    /**
     * Gets nextPaymentSum
     *
     * @return double|null
     */
    public function getNextPaymentSum()
    {
        return $this->container['nextPaymentSum'];
    }

    /**
     * Sets nextPaymentSum
     *
     * @param double|null $nextPaymentSum Next scheduled payment amount
     *
     * @return $this
     */
    public function setNextPaymentSum($nextPaymentSum)
    {
        $this->container['nextPaymentSum'] = $nextPaymentSum;

        return $this;
    }

    /**
     * Gets nrOfScheduledPayments
     *
     * @return int|null
     */
    public function getNrOfScheduledPayments()
    {
        return $this->container['nrOfScheduledPayments'];
    }

    /**
     * Sets nrOfScheduledPayments
     *
     * @param int|null $nrOfScheduledPayments Total number of scheduled payments
     *
     * @return $this
     */
    public function setNrOfScheduledPayments($nrOfScheduledPayments)
    {
        $this->container['nrOfScheduledPayments'] = $nrOfScheduledPayments;

        return $this;
    }

    /**
     * Gets lastPaymentDate
     *
     * @return \DateTime|null
     */
    public function getLastPaymentDate()
    {
        return $this->container['lastPaymentDate'];
    }

    /**
     * Sets lastPaymentDate
     *
     * @param \DateTime|null $lastPaymentDate Last payment date
     *
     * @return $this
     */
    public function setLastPaymentDate($lastPaymentDate)
    {
        $this->container['lastPaymentDate'] = $lastPaymentDate;

        return $this;
    }

    /**
     * Gets principalRepaid
     *
     * @return double|null
     */
    public function getPrincipalRepaid()
    {
        return $this->container['principalRepaid'];
    }

    /**
     * Sets principalRepaid
     *
     * @param double|null $principalRepaid Total principal repaid amount
     *
     * @return $this
     */
    public function setPrincipalRepaid($principalRepaid)
    {
        $this->container['principalRepaid'] = $principalRepaid;

        return $this;
    }

    /**
     * Gets interestRepaid
     *
     * @return double|null
     */
    public function getInterestRepaid()
    {
        return $this->container['interestRepaid'];
    }

    /**
     * Sets interestRepaid
     *
     * @param double|null $interestRepaid Total interest repaid amount
     *
     * @return $this
     */
    public function setInterestRepaid($interestRepaid)
    {
        $this->container['interestRepaid'] = $interestRepaid;

        return $this;
    }

    /**
     * Gets lateAmountPaid
     *
     * @return double|null
     */
    public function getLateAmountPaid()
    {
        return $this->container['lateAmountPaid'];
    }

    /**
     * Sets lateAmountPaid
     *
     * @param double|null $lateAmountPaid Total late charges paid amount
     *
     * @return $this
     */
    public function setLateAmountPaid($lateAmountPaid)
    {
        $this->container['lateAmountPaid'] = $lateAmountPaid;

        return $this;
    }

    /**
     * Gets principalRemaining
     *
     * @return double|null
     */
    public function getPrincipalRemaining()
    {
        return $this->container['principalRemaining'];
    }

    /**
     * Sets principalRemaining
     *
     * @param double|null $principalRemaining Remaining principal amount
     *
     * @return $this
     */
    public function setPrincipalRemaining($principalRemaining)
    {
        $this->container['principalRemaining'] = $principalRemaining;

        return $this;
    }

    /**
     * Gets principalLateAmount
     *
     * @return double|null
     */
    public function getPrincipalLateAmount()
    {
        return $this->container['principalLateAmount'];
    }

    /**
     * Sets principalLateAmount
     *
     * @param double|null $principalLateAmount Principal debt amount
     *
     * @return $this
     */
    public function setPrincipalLateAmount($principalLateAmount)
    {
        $this->container['principalLateAmount'] = $principalLateAmount;

        return $this;
    }

    /**
     * Gets interestLateAmount
     *
     * @return double|null
     */
    public function getInterestLateAmount()
    {
        return $this->container['interestLateAmount'];
    }

    /**
     * Sets interestLateAmount
     *
     * @param double|null $interestLateAmount Interest debt amount
     *
     * @return $this
     */
    public function setInterestLateAmount($interestLateAmount)
    {
        $this->container['interestLateAmount'] = $interestLateAmount;

        return $this;
    }

    /**
     * Gets penaltyLateAmount
     *
     * @return double|null
     */
    public function getPenaltyLateAmount()
    {
        return $this->container['penaltyLateAmount'];
    }

    /**
     * Sets penaltyLateAmount
     *
     * @param double|null $penaltyLateAmount Late charges debt amount
     *
     * @return $this
     */
    public function setPenaltyLateAmount($penaltyLateAmount)
    {
        $this->container['penaltyLateAmount'] = $penaltyLateAmount;

        return $this;
    }

    /**
     * Gets lateAmountTotal
     *
     * @return double|null
     */
    public function getLateAmountTotal()
    {
        return $this->container['lateAmountTotal'];
    }

    /**
     * Sets lateAmountTotal
     *
     * @param double|null $lateAmountTotal Late amount total
     *
     * @return $this
     */
    public function setLateAmountTotal($lateAmountTotal)
    {
        $this->container['lateAmountTotal'] = $lateAmountTotal;

        return $this;
    }

    /**
     * Gets principalWriteOffAmount
     *
     * @return double|null
     */
    public function getPrincipalWriteOffAmount()
    {
        return $this->container['principalWriteOffAmount'];
    }

    /**
     * Sets principalWriteOffAmount
     *
     * @param double|null $principalWriteOffAmount Total amount of principal written off
     *
     * @return $this
     */
    public function setPrincipalWriteOffAmount($principalWriteOffAmount)
    {
        $this->container['principalWriteOffAmount'] = $principalWriteOffAmount;

        return $this;
    }

    /**
     * Gets interestWriteOffAmount
     *
     * @return double|null
     */
    public function getInterestWriteOffAmount()
    {
        return $this->container['interestWriteOffAmount'];
    }

    /**
     * Sets interestWriteOffAmount
     *
     * @param double|null $interestWriteOffAmount Total amount of interest written off
     *
     * @return $this
     */
    public function setInterestWriteOffAmount($interestWriteOffAmount)
    {
        $this->container['interestWriteOffAmount'] = $interestWriteOffAmount;

        return $this;
    }

    /**
     * Gets penaltyWriteOffAmount
     *
     * @return double|null
     */
    public function getPenaltyWriteOffAmount()
    {
        return $this->container['penaltyWriteOffAmount'];
    }

    /**
     * Sets penaltyWriteOffAmount
     *
     * @param double|null $penaltyWriteOffAmount Total amount of penalty written off
     *
     * @return $this
     */
    public function setPenaltyWriteOffAmount($penaltyWriteOffAmount)
    {
        $this->container['penaltyWriteOffAmount'] = $penaltyWriteOffAmount;

        return $this;
    }

    /**
     * Gets debtServicingCostMainAmount
     *
     * @return double|null
     */
    public function getDebtServicingCostMainAmount()
    {
        return $this->container['debtServicingCostMainAmount'];
    }

    /**
     * Sets debtServicingCostMainAmount
     *
     * @param double|null $debtServicingCostMainAmount Total amount of principal debt servicing cost
     *
     * @return $this
     */
    public function setDebtServicingCostMainAmount($debtServicingCostMainAmount)
    {
        $this->container['debtServicingCostMainAmount'] = $debtServicingCostMainAmount;

        return $this;
    }

    /**
     * Gets debtServicingCostInterestAmount
     *
     * @return double|null
     */
    public function getDebtServicingCostInterestAmount()
    {
        return $this->container['debtServicingCostInterestAmount'];
    }

    /**
     * Sets debtServicingCostInterestAmount
     *
     * @param double|null $debtServicingCostInterestAmount Total amount of interest debt servicing cost
     *
     * @return $this
     */
    public function setDebtServicingCostInterestAmount($debtServicingCostInterestAmount)
    {
        $this->container['debtServicingCostInterestAmount'] = $debtServicingCostInterestAmount;

        return $this;
    }

    /**
     * Gets debtServicingCostPenaltyAmount
     *
     * @return double|null
     */
    public function getDebtServicingCostPenaltyAmount()
    {
        return $this->container['debtServicingCostPenaltyAmount'];
    }

    /**
     * Sets debtServicingCostPenaltyAmount
     *
     * @param double|null $debtServicingCostPenaltyAmount Total amount of penalty debt servicing cost
     *
     * @return $this
     */
    public function setDebtServicingCostPenaltyAmount($debtServicingCostPenaltyAmount)
    {
        $this->container['debtServicingCostPenaltyAmount'] = $debtServicingCostPenaltyAmount;

        return $this;
    }

    /**
     * Gets purchaseDate
     *
     * @return \DateTime|null
     */
    public function getPurchaseDate()
    {
        return $this->container['purchaseDate'];
    }

    /**
     * Sets purchaseDate
     *
     * @param \DateTime|null $purchaseDate Date when investment was made or purchased from second market
     *
     * @return $this
     */
    public function setPurchaseDate($purchaseDate)
    {
        $this->container['purchaseDate'] = $purchaseDate;

        return $this;
    }

    /**
     * Gets soldDate
     *
     * @return \DateTime|null
     */
    public function getSoldDate()
    {
        return $this->container['soldDate'];
    }

    /**
     * Sets soldDate
     *
     * @param \DateTime|null $soldDate Investment selling date
     *
     * @return $this
     */
    public function setSoldDate($soldDate)
    {
        $this->container['soldDate'] = $soldDate;

        return $this;
    }

    /**
     * Gets purchasePrice
     *
     * @return double|null
     */
    public function getPurchasePrice()
    {
        return $this->container['purchasePrice'];
    }

    /**
     * Sets purchasePrice
     *
     * @param double|null $purchasePrice Investment amount or secondary market purchase price
     *
     * @return $this
     */
    public function setPurchasePrice($purchasePrice)
    {
        $this->container['purchasePrice'] = $purchasePrice;

        return $this;
    }

    /**
     * Gets salePrice
     *
     * @return double|null
     */
    public function getSalePrice()
    {
        return $this->container['salePrice'];
    }

    /**
     * Sets salePrice
     *
     * @param double|null $salePrice SecondMarket sale price
     *
     * @return $this
     */
    public function setSalePrice($salePrice)
    {
        $this->container['salePrice'] = $salePrice;

        return $this;
    }

    /**
     * Gets listedInSecondMarketOn
     *
     * @return \DateTime|null
     */
    public function getListedInSecondMarketOn()
    {
        return $this->container['listedInSecondMarketOn'];
    }

    /**
     * Sets listedInSecondMarketOn
     *
     * @param \DateTime|null $listedInSecondMarketOn Date when item was listed on secondary market
     *
     * @return $this
     */
    public function setListedInSecondMarketOn($listedInSecondMarketOn)
    {
        $this->container['listedInSecondMarketOn'] = $listedInSecondMarketOn;

        return $this;
    }

    /**
     * Gets latestDebtManagementStage
     *
     * @return int|null
     */
    public function getLatestDebtManagementStage()
    {
        return $this->container['latestDebtManagementStage'];
    }

    /**
     * Sets latestDebtManagementStage
     *
     * @param int|null $latestDebtManagementStage Latest debt management stage
     *
     * @return $this
     */
    public function setLatestDebtManagementStage($latestDebtManagementStage)
    {
        $allowedValues = $this->getLatestDebtManagementStageAllowableValues();
        if (!is_null($latestDebtManagementStage) && !in_array($latestDebtManagementStage, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'latestDebtManagementStage', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['latestDebtManagementStage'] = $latestDebtManagementStage;

        return $this;
    }

    /**
     * Gets latestDebtManagementSubStage
     *
     * @return int|null
     */
    public function getLatestDebtManagementSubStage()
    {
        return $this->container['latestDebtManagementSubStage'];
    }

    /**
     * Sets latestDebtManagementSubStage
     *
     * @param int|null $latestDebtManagementSubStage 
     *
     * @return $this
     */
    public function setLatestDebtManagementSubStage($latestDebtManagementSubStage)
    {
        $allowedValues = $this->getLatestDebtManagementSubStageAllowableValues();
        if (!is_null($latestDebtManagementSubStage) && !in_array($latestDebtManagementSubStage, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'latestDebtManagementSubStage', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['latestDebtManagementSubStage'] = $latestDebtManagementSubStage;

        return $this;
    }

    /**
     * Gets latestDebtManagementStageType
     *
     * @return int|null
     */
    public function getLatestDebtManagementStageType()
    {
        return $this->container['latestDebtManagementStageType'];
    }

    /**
     * Sets latestDebtManagementStageType
     *
     * @param int|null $latestDebtManagementStageType Latest debt management stage type
     *
     * @return $this
     */
    public function setLatestDebtManagementStageType($latestDebtManagementStageType)
    {
        $allowedValues = $this->getLatestDebtManagementStageTypeAllowableValues();
        if (!is_null($latestDebtManagementStageType) && !in_array($latestDebtManagementStageType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'latestDebtManagementStageType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['latestDebtManagementStageType'] = $latestDebtManagementStageType;

        return $this;
    }

    /**
     * Gets latestDebtManagementDate
     *
     * @return \DateTime|null
     */
    public function getLatestDebtManagementDate()
    {
        return $this->container['latestDebtManagementDate'];
    }

    /**
     * Sets latestDebtManagementDate
     *
     * @param \DateTime|null $latestDebtManagementDate Latest debt management date
     *
     * @return $this
     */
    public function setLatestDebtManagementDate($latestDebtManagementDate)
    {
        $this->container['latestDebtManagementDate'] = $latestDebtManagementDate;

        return $this;
    }

    /**
     * Gets noteLoanTransfersMainAmount
     *
     * @return double|null
     */
    public function getNoteLoanTransfersMainAmount()
    {
        return $this->container['noteLoanTransfersMainAmount'];
    }

    /**
     * Sets noteLoanTransfersMainAmount
     *
     * @param double|null $noteLoanTransfersMainAmount Note owner received loan transfers principal amount
     *
     * @return $this
     */
    public function setNoteLoanTransfersMainAmount($noteLoanTransfersMainAmount)
    {
        $this->container['noteLoanTransfersMainAmount'] = $noteLoanTransfersMainAmount;

        return $this;
    }

    /**
     * Gets noteLoanTransfersInterestAmount
     *
     * @return double|null
     */
    public function getNoteLoanTransfersInterestAmount()
    {
        return $this->container['noteLoanTransfersInterestAmount'];
    }

    /**
     * Sets noteLoanTransfersInterestAmount
     *
     * @param double|null $noteLoanTransfersInterestAmount Note owner received loan transfers interest amount
     *
     * @return $this
     */
    public function setNoteLoanTransfersInterestAmount($noteLoanTransfersInterestAmount)
    {
        $this->container['noteLoanTransfersInterestAmount'] = $noteLoanTransfersInterestAmount;

        return $this;
    }

    /**
     * Gets noteLoanLateChargesPaid
     *
     * @return double|null
     */
    public function getNoteLoanLateChargesPaid()
    {
        return $this->container['noteLoanLateChargesPaid'];
    }

    /**
     * Sets noteLoanLateChargesPaid
     *
     * @param double|null $noteLoanLateChargesPaid Note owner received loan transfers penalties amount
     *
     * @return $this
     */
    public function setNoteLoanLateChargesPaid($noteLoanLateChargesPaid)
    {
        $this->container['noteLoanLateChargesPaid'] = $noteLoanLateChargesPaid;

        return $this;
    }

    /**
     * Gets noteLoanTransfersEarningsAmount
     *
     * @return double|null
     */
    public function getNoteLoanTransfersEarningsAmount()
    {
        return $this->container['noteLoanTransfersEarningsAmount'];
    }

    /**
     * Sets noteLoanTransfersEarningsAmount
     *
     * @param double|null $noteLoanTransfersEarningsAmount Note owner received loan transfers earned interest, penalties total amount
     *
     * @return $this
     */
    public function setNoteLoanTransfersEarningsAmount($noteLoanTransfersEarningsAmount)
    {
        $this->container['noteLoanTransfersEarningsAmount'] = $noteLoanTransfersEarningsAmount;

        return $this;
    }

    /**
     * Gets noteLoanTransfersTotalRepaimentsAmount
     *
     * @return double|null
     */
    public function getNoteLoanTransfersTotalRepaimentsAmount()
    {
        return $this->container['noteLoanTransfersTotalRepaimentsAmount'];
    }

    /**
     * Sets noteLoanTransfersTotalRepaimentsAmount
     *
     * @param double|null $noteLoanTransfersTotalRepaimentsAmount Note owner received loan transfers total amount
     *
     * @return $this
     */
    public function setNoteLoanTransfersTotalRepaimentsAmount($noteLoanTransfersTotalRepaimentsAmount)
    {
        $this->container['noteLoanTransfersTotalRepaimentsAmount'] = $noteLoanTransfersTotalRepaimentsAmount;

        return $this;
    }

    /**
     * Gets boughtFromId
     *
     * @return string|null
     */
    public function getBoughtFromId()
    {
        return $this->container['boughtFromId'];
    }

    /**
     * Sets boughtFromId
     *
     * @param string|null $boughtFromId 
     *
     * @return $this
     */
    public function setBoughtFromId($boughtFromId)
    {
        $this->container['boughtFromId'] = $boughtFromId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


