<?php
/**
 * BidApi
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CedricZiel\OpenAPI\BondoraPHP\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use CedricZiel\OpenAPI\BondoraPHP\ApiException;
use CedricZiel\OpenAPI\BondoraPHP\Configuration;
use CedricZiel\OpenAPI\BondoraPHP\HeaderSelector;
use CedricZiel\OpenAPI\BondoraPHP\ObjectSerializer;

/**
 * BidApi Class Doc Comment
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BidApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bidCancelBid
     *
     * Cancel the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult
     */
    public function bidCancelBid($id)
    {
        list($response) = $this->bidCancelBidWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation bidCancelBidWithHttpInfo
     *
     * Cancel the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function bidCancelBidWithHttpInfo($id)
    {
        $request = $this->bidCancelBidRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 202:
                    if ('\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bidCancelBidAsync
     *
     * Cancel the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidCancelBidAsync($id)
    {
        return $this->bidCancelBidAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bidCancelBidAsyncWithHttpInfo
     *
     * Cancel the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidCancelBidAsyncWithHttpInfo($id)
    {
        $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResult';
        $request = $this->bidCancelBidRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bidCancelBid'
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bidCancelBidRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling bidCancelBid'
            );
        }

        $resourcePath = '/api/v1/bid/{id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bidGetBid
     *
     * Get the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid
     */
    public function bidGetBid($id)
    {
        list($response) = $this->bidGetBidWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation bidGetBidWithHttpInfo
     *
     * Get the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid, HTTP status code, HTTP response headers (array of strings)
     */
    public function bidGetBidWithHttpInfo($id)
    {
        $request = $this->bidGetBidRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bidGetBidAsync
     *
     * Get the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidGetBidAsync($id)
    {
        return $this->bidGetBidAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bidGetBidAsyncWithHttpInfo
     *
     * Get the Bid
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidGetBidAsyncWithHttpInfo($id)
    {
        $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBid';
        $request = $this->bidGetBidRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bidGetBid'
     *
     * @param  string $id Bid identificator (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bidGetBidRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling bidGetBid'
            );
        }

        $resourcePath = '/api/v1/bid/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bidGetBidSummaries
     *
     * Gets list of bids the investor has made.
     *
     * @param  int $requestBidStatusCode Bid status code (optional)
     * @param  \DateTime $requestStartDate Start date (optional)
     * @param  \DateTime $requestEndDate End date (optional)
     * @param  int $requestPageSize Max items in result, up to 20000 (optional)
     * @param  int $requestPageNr Result page nr (optional)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids
     */
    public function bidGetBidSummaries($requestBidStatusCode = null, $requestStartDate = null, $requestEndDate = null, $requestPageSize = null, $requestPageNr = null)
    {
        list($response) = $this->bidGetBidSummariesWithHttpInfo($requestBidStatusCode, $requestStartDate, $requestEndDate, $requestPageSize, $requestPageNr);
        return $response;
    }

    /**
     * Operation bidGetBidSummariesWithHttpInfo
     *
     * Gets list of bids the investor has made.
     *
     * @param  int $requestBidStatusCode Bid status code (optional)
     * @param  \DateTime $requestStartDate Start date (optional)
     * @param  \DateTime $requestEndDate End date (optional)
     * @param  int $requestPageSize Max items in result, up to 20000 (optional)
     * @param  int $requestPageNr Result page nr (optional)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids, HTTP status code, HTTP response headers (array of strings)
     */
    public function bidGetBidSummariesWithHttpInfo($requestBidStatusCode = null, $requestStartDate = null, $requestEndDate = null, $requestPageSize = null, $requestPageNr = null)
    {
        $request = $this->bidGetBidSummariesRequest($requestBidStatusCode, $requestStartDate, $requestEndDate, $requestPageSize, $requestPageNr);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bidGetBidSummariesAsync
     *
     * Gets list of bids the investor has made.
     *
     * @param  int $requestBidStatusCode Bid status code (optional)
     * @param  \DateTime $requestStartDate Start date (optional)
     * @param  \DateTime $requestEndDate End date (optional)
     * @param  int $requestPageSize Max items in result, up to 20000 (optional)
     * @param  int $requestPageNr Result page nr (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidGetBidSummariesAsync($requestBidStatusCode = null, $requestStartDate = null, $requestEndDate = null, $requestPageSize = null, $requestPageNr = null)
    {
        return $this->bidGetBidSummariesAsyncWithHttpInfo($requestBidStatusCode, $requestStartDate, $requestEndDate, $requestPageSize, $requestPageNr)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bidGetBidSummariesAsyncWithHttpInfo
     *
     * Gets list of bids the investor has made.
     *
     * @param  int $requestBidStatusCode Bid status code (optional)
     * @param  \DateTime $requestStartDate Start date (optional)
     * @param  \DateTime $requestEndDate End date (optional)
     * @param  int $requestPageSize Max items in result, up to 20000 (optional)
     * @param  int $requestPageNr Result page nr (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidGetBidSummariesAsyncWithHttpInfo($requestBidStatusCode = null, $requestStartDate = null, $requestEndDate = null, $requestPageSize = null, $requestPageNr = null)
    {
        $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultBids';
        $request = $this->bidGetBidSummariesRequest($requestBidStatusCode, $requestStartDate, $requestEndDate, $requestPageSize, $requestPageNr);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bidGetBidSummaries'
     *
     * @param  int $requestBidStatusCode Bid status code (optional)
     * @param  \DateTime $requestStartDate Start date (optional)
     * @param  \DateTime $requestEndDate End date (optional)
     * @param  int $requestPageSize Max items in result, up to 20000 (optional)
     * @param  int $requestPageNr Result page nr (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bidGetBidSummariesRequest($requestBidStatusCode = null, $requestStartDate = null, $requestEndDate = null, $requestPageSize = null, $requestPageNr = null)
    {
        if ($requestPageSize !== null && $requestPageSize > 20000) {
            throw new \InvalidArgumentException('invalid value for "$requestPageSize" when calling BidApi.bidGetBidSummaries, must be smaller than or equal to 20000.');
        }
        if ($requestPageSize !== null && $requestPageSize < 1) {
            throw new \InvalidArgumentException('invalid value for "$requestPageSize" when calling BidApi.bidGetBidSummaries, must be bigger than or equal to 1.');
        }

        if ($requestPageNr !== null && $requestPageNr > 2147483647) {
            throw new \InvalidArgumentException('invalid value for "$requestPageNr" when calling BidApi.bidGetBidSummaries, must be smaller than or equal to 2147483647.');
        }
        if ($requestPageNr !== null && $requestPageNr < 1) {
            throw new \InvalidArgumentException('invalid value for "$requestPageNr" when calling BidApi.bidGetBidSummaries, must be bigger than or equal to 1.');
        }


        $resourcePath = '/api/v1/bids';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($requestBidStatusCode !== null) {
            $queryParams['request.bidStatusCode'] = ObjectSerializer::toQueryValue($requestBidStatusCode);
        }
        // query params
        if ($requestStartDate !== null) {
            $queryParams['request.startDate'] = ObjectSerializer::toQueryValue($requestStartDate);
        }
        // query params
        if ($requestEndDate !== null) {
            $queryParams['request.endDate'] = ObjectSerializer::toQueryValue($requestEndDate);
        }
        // query params
        if ($requestPageSize !== null) {
            $queryParams['request.pageSize'] = ObjectSerializer::toQueryValue($requestPageSize);
        }
        // query params
        if ($requestPageNr !== null) {
            $queryParams['request.pageNr'] = ObjectSerializer::toQueryValue($requestPageNr);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bidMakeBids
     *
     * Makes bid(s) into specified auction(s).
     *
     * @param  \CedricZiel\OpenAPI\BondoraPHP\Model\BidRequest $bidRequest bidRequest (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids
     */
    public function bidMakeBids($bidRequest)
    {
        list($response) = $this->bidMakeBidsWithHttpInfo($bidRequest);
        return $response;
    }

    /**
     * Operation bidMakeBidsWithHttpInfo
     *
     * Makes bid(s) into specified auction(s).
     *
     * @param  \CedricZiel\OpenAPI\BondoraPHP\Model\BidRequest $bidRequest (required)
     *
     * @throws \CedricZiel\OpenAPI\BondoraPHP\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids, HTTP status code, HTTP response headers (array of strings)
     */
    public function bidMakeBidsWithHttpInfo($bidRequest)
    {
        $request = $this->bidMakeBidsRequest($bidRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 202:
                    if ('\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bidMakeBidsAsync
     *
     * Makes bid(s) into specified auction(s).
     *
     * @param  \CedricZiel\OpenAPI\BondoraPHP\Model\BidRequest $bidRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidMakeBidsAsync($bidRequest)
    {
        return $this->bidMakeBidsAsyncWithHttpInfo($bidRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bidMakeBidsAsyncWithHttpInfo
     *
     * Makes bid(s) into specified auction(s).
     *
     * @param  \CedricZiel\OpenAPI\BondoraPHP\Model\BidRequest $bidRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bidMakeBidsAsyncWithHttpInfo($bidRequest)
    {
        $returnType = '\CedricZiel\OpenAPI\BondoraPHP\Model\ApiResultMakeBids';
        $request = $this->bidMakeBidsRequest($bidRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bidMakeBids'
     *
     * @param  \CedricZiel\OpenAPI\BondoraPHP\Model\BidRequest $bidRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bidMakeBidsRequest($bidRequest)
    {
        // verify the required parameter 'bidRequest' is set
        if ($bidRequest === null || (is_array($bidRequest) && count($bidRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bidRequest when calling bidMakeBids'
            );
        }

        $resourcePath = '/api/v1/bid';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($bidRequest)) {
            $_tempBody = $bidRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
