<?php
/**
 * AuctionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use PHPUnit\Framework\TestCase;

/**
 * AuctionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request object for filtering auctions
 * @package     CedricZiel\OpenAPI\BondoraPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AuctionRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuctionRequest"
     */
    public function testAuctionRequest()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "ratings"
     */
    public function testPropertyRatings()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "sumMin"
     */
    public function testPropertySumMin()
    {
    }

    /**
     * Test attribute "sumMax"
     */
    public function testPropertySumMax()
    {
    }

    /**
     * Test attribute "terms"
     */
    public function testPropertyTerms()
    {
    }

    /**
     * Test attribute "ageMin"
     */
    public function testPropertyAgeMin()
    {
    }

    /**
     * Test attribute "ageMax"
     */
    public function testPropertyAgeMax()
    {
    }

    /**
     * Test attribute "loanNumber"
     */
    public function testPropertyLoanNumber()
    {
    }

    /**
     * Test attribute "userName"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "applicationDateFrom"
     */
    public function testPropertyApplicationDateFrom()
    {
    }

    /**
     * Test attribute "applicationDateTo"
     */
    public function testPropertyApplicationDateTo()
    {
    }

    /**
     * Test attribute "creditScoreMin"
     */
    public function testPropertyCreditScoreMin()
    {
    }

    /**
     * Test attribute "creditScoreMax"
     */
    public function testPropertyCreditScoreMax()
    {
    }

    /**
     * Test attribute "creditScoresEeMini"
     */
    public function testPropertyCreditScoresEeMini()
    {
    }

    /**
     * Test attribute "interestMin"
     */
    public function testPropertyInterestMin()
    {
    }

    /**
     * Test attribute "interestMax"
     */
    public function testPropertyInterestMax()
    {
    }

    /**
     * Test attribute "incomeTotalMin"
     */
    public function testPropertyIncomeTotalMin()
    {
    }

    /**
     * Test attribute "incomeTotalMax"
     */
    public function testPropertyIncomeTotalMax()
    {
    }

    /**
     * Test attribute "modelVersion"
     */
    public function testPropertyModelVersion()
    {
    }

    /**
     * Test attribute "expectedLossMin"
     */
    public function testPropertyExpectedLossMin()
    {
    }

    /**
     * Test attribute "expectedLossMax"
     */
    public function testPropertyExpectedLossMax()
    {
    }

    /**
     * Test attribute "listedOnUTCFrom"
     */
    public function testPropertyListedOnUTCFrom()
    {
    }

    /**
     * Test attribute "listedOnUTCTo"
     */
    public function testPropertyListedOnUTCTo()
    {
    }

    /**
     * Test attribute "pageSize"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "pageNr"
     */
    public function testPropertyPageNr()
    {
    }
}
