<?php
/**
 * BorrowerHistoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use PHPUnit\Framework\TestCase;

/**
 * BorrowerHistoryTest Class Doc Comment
 *
 * @category    Class
 * @description Borrower&#39;s history
 * @package     CedricZiel\OpenAPI\BondoraPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BorrowerHistoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BorrowerHistory"
     */
    public function testBorrowerHistory()
    {
    }

    /**
     * Test attribute "overdue"
     */
    public function testPropertyOverdue()
    {
    }

    /**
     * Test attribute "principalRepaid"
     */
    public function testPropertyPrincipalRepaid()
    {
    }

    /**
     * Test attribute "interestRepaid"
     */
    public function testPropertyInterestRepaid()
    {
    }

    /**
     * Test attribute "lateChargesRepaid"
     */
    public function testPropertyLateChargesRepaid()
    {
    }

    /**
     * Test attribute "repaimentsTotal"
     */
    public function testPropertyRepaimentsTotal()
    {
    }

    /**
     * Test attribute "issuedLoans"
     */
    public function testPropertyIssuedLoans()
    {
    }

    /**
     * Test attribute "issuedLoanAmount"
     */
    public function testPropertyIssuedLoanAmount()
    {
    }
}
