<?php
/**
 * MyAccountBalanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use PHPUnit\Framework\TestCase;

/**
 * MyAccountBalanceTest Class Doc Comment
 *
 * @category    Class
 * @description My account balance information
 * @package     CedricZiel\OpenAPI\BondoraPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MyAccountBalanceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MyAccountBalance"
     */
    public function testMyAccountBalance()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "reserved"
     */
    public function testPropertyReserved()
    {
    }

    /**
     * Test attribute "bidRequestAmount"
     */
    public function testPropertyBidRequestAmount()
    {
    }

    /**
     * Test attribute "totalAvailable"
     */
    public function testPropertyTotalAvailable()
    {
    }

    /**
     * Test attribute "goGrowAccounts"
     */
    public function testPropertyGoGrowAccounts()
    {
    }
}
