<?php
/**
 * MyInvestmentItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use PHPUnit\Framework\TestCase;

/**
 * MyInvestmentItemTest Class Doc Comment
 *
 * @category    Class
 * @description MyInvestments list item&#39;s information
 * @package     CedricZiel\OpenAPI\BondoraPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MyInvestmentItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MyInvestmentItem"
     */
    public function testMyInvestmentItem()
    {
    }

    /**
     * Test attribute "loanPartId"
     */
    public function testPropertyLoanPartId()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "auctionId"
     */
    public function testPropertyAuctionId()
    {
    }

    /**
     * Test attribute "auctionName"
     */
    public function testPropertyAuctionName()
    {
    }

    /**
     * Test attribute "auctionNumber"
     */
    public function testPropertyAuctionNumber()
    {
    }

    /**
     * Test attribute "auctionBidNumber"
     */
    public function testPropertyAuctionBidNumber()
    {
    }

    /**
     * Test attribute "investmentNumber"
     */
    public function testPropertyInvestmentNumber()
    {
    }

    /**
     * Test attribute "auctionBidType"
     */
    public function testPropertyAuctionBidType()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "creditScore"
     */
    public function testPropertyCreditScore()
    {
    }

    /**
     * Test attribute "creditScoreEsMicroL"
     */
    public function testPropertyCreditScoreEsMicroL()
    {
    }

    /**
     * Test attribute "creditScoreEsEquifaxRisk"
     */
    public function testPropertyCreditScoreEsEquifaxRisk()
    {
    }

    /**
     * Test attribute "creditScoreFiAsiakasTietoRiskGrade"
     */
    public function testPropertyCreditScoreFiAsiakasTietoRiskGrade()
    {
    }

    /**
     * Test attribute "creditScoreEeMini"
     */
    public function testPropertyCreditScoreEeMini()
    {
    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {
    }

    /**
     * Test attribute "interest"
     */
    public function testPropertyInterest()
    {
    }

    /**
     * Test attribute "useOfLoan"
     */
    public function testPropertyUseOfLoan()
    {
    }

    /**
     * Test attribute "incomeVerificationStatus"
     */
    public function testPropertyIncomeVerificationStatus()
    {
    }

    /**
     * Test attribute "loanId"
     */
    public function testPropertyLoanId()
    {
    }

    /**
     * Test attribute "loanStatusCode"
     */
    public function testPropertyLoanStatusCode()
    {
    }

    /**
     * Test attribute "loanStatusActiveFrom"
     */
    public function testPropertyLoanStatusActiveFrom()
    {
    }

    /**
     * Test attribute "userName"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "dateOfBirth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "signedDate"
     */
    public function testPropertySignedDate()
    {
    }

    /**
     * Test attribute "reScheduledOn"
     */
    public function testPropertyReScheduledOn()
    {
    }

    /**
     * Test attribute "debtOccuredOn"
     */
    public function testPropertyDebtOccuredOn()
    {
    }

    /**
     * Test attribute "debtOccuredOnForSecondary"
     */
    public function testPropertyDebtOccuredOnForSecondary()
    {
    }

    /**
     * Test attribute "loanDuration"
     */
    public function testPropertyLoanDuration()
    {
    }

    /**
     * Test attribute "nextPaymentNr"
     */
    public function testPropertyNextPaymentNr()
    {
    }

    /**
     * Test attribute "nextPaymentDate"
     */
    public function testPropertyNextPaymentDate()
    {
    }

    /**
     * Test attribute "nextPaymentSum"
     */
    public function testPropertyNextPaymentSum()
    {
    }

    /**
     * Test attribute "nrOfScheduledPayments"
     */
    public function testPropertyNrOfScheduledPayments()
    {
    }

    /**
     * Test attribute "lastPaymentDate"
     */
    public function testPropertyLastPaymentDate()
    {
    }

    /**
     * Test attribute "principalRepaid"
     */
    public function testPropertyPrincipalRepaid()
    {
    }

    /**
     * Test attribute "interestRepaid"
     */
    public function testPropertyInterestRepaid()
    {
    }

    /**
     * Test attribute "lateAmountPaid"
     */
    public function testPropertyLateAmountPaid()
    {
    }

    /**
     * Test attribute "principalRemaining"
     */
    public function testPropertyPrincipalRemaining()
    {
    }

    /**
     * Test attribute "principalLateAmount"
     */
    public function testPropertyPrincipalLateAmount()
    {
    }

    /**
     * Test attribute "interestLateAmount"
     */
    public function testPropertyInterestLateAmount()
    {
    }

    /**
     * Test attribute "penaltyLateAmount"
     */
    public function testPropertyPenaltyLateAmount()
    {
    }

    /**
     * Test attribute "lateAmountTotal"
     */
    public function testPropertyLateAmountTotal()
    {
    }

    /**
     * Test attribute "principalWriteOffAmount"
     */
    public function testPropertyPrincipalWriteOffAmount()
    {
    }

    /**
     * Test attribute "interestWriteOffAmount"
     */
    public function testPropertyInterestWriteOffAmount()
    {
    }

    /**
     * Test attribute "penaltyWriteOffAmount"
     */
    public function testPropertyPenaltyWriteOffAmount()
    {
    }

    /**
     * Test attribute "debtServicingCostMainAmount"
     */
    public function testPropertyDebtServicingCostMainAmount()
    {
    }

    /**
     * Test attribute "debtServicingCostInterestAmount"
     */
    public function testPropertyDebtServicingCostInterestAmount()
    {
    }

    /**
     * Test attribute "debtServicingCostPenaltyAmount"
     */
    public function testPropertyDebtServicingCostPenaltyAmount()
    {
    }

    /**
     * Test attribute "purchaseDate"
     */
    public function testPropertyPurchaseDate()
    {
    }

    /**
     * Test attribute "soldDate"
     */
    public function testPropertySoldDate()
    {
    }

    /**
     * Test attribute "purchasePrice"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "salePrice"
     */
    public function testPropertySalePrice()
    {
    }

    /**
     * Test attribute "listedInSecondMarketOn"
     */
    public function testPropertyListedInSecondMarketOn()
    {
    }

    /**
     * Test attribute "latestDebtManagementStage"
     */
    public function testPropertyLatestDebtManagementStage()
    {
    }

    /**
     * Test attribute "latestDebtManagementSubStage"
     */
    public function testPropertyLatestDebtManagementSubStage()
    {
    }

    /**
     * Test attribute "latestDebtManagementStageType"
     */
    public function testPropertyLatestDebtManagementStageType()
    {
    }

    /**
     * Test attribute "latestDebtManagementDate"
     */
    public function testPropertyLatestDebtManagementDate()
    {
    }

    /**
     * Test attribute "noteLoanTransfersMainAmount"
     */
    public function testPropertyNoteLoanTransfersMainAmount()
    {
    }

    /**
     * Test attribute "noteLoanTransfersInterestAmount"
     */
    public function testPropertyNoteLoanTransfersInterestAmount()
    {
    }

    /**
     * Test attribute "noteLoanLateChargesPaid"
     */
    public function testPropertyNoteLoanLateChargesPaid()
    {
    }

    /**
     * Test attribute "noteLoanTransfersEarningsAmount"
     */
    public function testPropertyNoteLoanTransfersEarningsAmount()
    {
    }

    /**
     * Test attribute "noteLoanTransfersTotalRepaimentsAmount"
     */
    public function testPropertyNoteLoanTransfersTotalRepaimentsAmount()
    {
    }

    /**
     * Test attribute "boughtFromId"
     */
    public function testPropertyBoughtFromId()
    {
    }
}
