<?php
/**
 * SecondMarketRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use PHPUnit\Framework\TestCase;

/**
 * SecondMarketRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request object for filtering secondary market
 * @package     CedricZiel\OpenAPI\BondoraPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SecondMarketRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SecondMarketRequest"
     */
    public function testSecondMarketRequest()
    {
    }

    /**
     * Test attribute "loanIssuedDateFrom"
     */
    public function testPropertyLoanIssuedDateFrom()
    {
    }

    /**
     * Test attribute "loanIssuedDateTo"
     */
    public function testPropertyLoanIssuedDateTo()
    {
    }

    /**
     * Test attribute "principalMin"
     */
    public function testPropertyPrincipalMin()
    {
    }

    /**
     * Test attribute "principalMax"
     */
    public function testPropertyPrincipalMax()
    {
    }

    /**
     * Test attribute "interestMin"
     */
    public function testPropertyInterestMin()
    {
    }

    /**
     * Test attribute "interestMax"
     */
    public function testPropertyInterestMax()
    {
    }

    /**
     * Test attribute "lengthMax"
     */
    public function testPropertyLengthMax()
    {
    }

    /**
     * Test attribute "lengthMin"
     */
    public function testPropertyLengthMin()
    {
    }

    /**
     * Test attribute "hasDebt"
     */
    public function testPropertyHasDebt()
    {
    }

    /**
     * Test attribute "loanStatusCode"
     */
    public function testPropertyLoanStatusCode()
    {
    }

    /**
     * Test attribute "loanDebtManagementStageType"
     */
    public function testPropertyLoanDebtManagementStageType()
    {
    }

    /**
     * Test attribute "loanDebtManagementDateActiveFrom"
     */
    public function testPropertyLoanDebtManagementDateActiveFrom()
    {
    }

    /**
     * Test attribute "loanDebtManagementDateActiveTo"
     */
    public function testPropertyLoanDebtManagementDateActiveTo()
    {
    }

    /**
     * Test attribute "latePrincipalAmountMin"
     */
    public function testPropertyLatePrincipalAmountMin()
    {
    }

    /**
     * Test attribute "latePrincipalAmountMax"
     */
    public function testPropertyLatePrincipalAmountMax()
    {
    }

    /**
     * Test attribute "priceMin"
     */
    public function testPropertyPriceMin()
    {
    }

    /**
     * Test attribute "priceMax"
     */
    public function testPropertyPriceMax()
    {
    }

    /**
     * Test attribute "useOfLoan"
     */
    public function testPropertyUseOfLoan()
    {
    }

    /**
     * Test attribute "hasNewSchedule"
     */
    public function testPropertyHasNewSchedule()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "ratings"
     */
    public function testPropertyRatings()
    {
    }

    /**
     * Test attribute "creditScoreMin"
     */
    public function testPropertyCreditScoreMin()
    {
    }

    /**
     * Test attribute "creditScoreMax"
     */
    public function testPropertyCreditScoreMax()
    {
    }

    /**
     * Test attribute "userName"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "ageMin"
     */
    public function testPropertyAgeMin()
    {
    }

    /**
     * Test attribute "ageMax"
     */
    public function testPropertyAgeMax()
    {
    }

    /**
     * Test attribute "incomeVerificationStatus"
     */
    public function testPropertyIncomeVerificationStatus()
    {
    }

    /**
     * Test attribute "showMyItems"
     */
    public function testPropertyShowMyItems()
    {
    }

    /**
     * Test attribute "auctionId"
     */
    public function testPropertyAuctionId()
    {
    }

    /**
     * Test attribute "listedOnDateFrom"
     */
    public function testPropertyListedOnDateFrom()
    {
    }

    /**
     * Test attribute "listedOnDateTo"
     */
    public function testPropertyListedOnDateTo()
    {
    }

    /**
     * Test attribute "debtOccuredOnFrom"
     */
    public function testPropertyDebtOccuredOnFrom()
    {
    }

    /**
     * Test attribute "debtOccuredOnTo"
     */
    public function testPropertyDebtOccuredOnTo()
    {
    }

    /**
     * Test attribute "debtOccuredOnForSecondaryFrom"
     */
    public function testPropertyDebtOccuredOnForSecondaryFrom()
    {
    }

    /**
     * Test attribute "debtOccuredOnForSecondaryTo"
     */
    public function testPropertyDebtOccuredOnForSecondaryTo()
    {
    }

    /**
     * Test attribute "defaultedDateFrom"
     */
    public function testPropertyDefaultedDateFrom()
    {
    }

    /**
     * Test attribute "defaultedDateTo"
     */
    public function testPropertyDefaultedDateTo()
    {
    }

    /**
     * Test attribute "rescheduledFrom"
     */
    public function testPropertyRescheduledFrom()
    {
    }

    /**
     * Test attribute "rescheduledTo"
     */
    public function testPropertyRescheduledTo()
    {
    }

    /**
     * Test attribute "lastPaymentDateFrom"
     */
    public function testPropertyLastPaymentDateFrom()
    {
    }

    /**
     * Test attribute "lastPaymentDateTo"
     */
    public function testPropertyLastPaymentDateTo()
    {
    }

    /**
     * Test attribute "nextPaymentDateFrom"
     */
    public function testPropertyNextPaymentDateFrom()
    {
    }

    /**
     * Test attribute "nextPaymentDateTo"
     */
    public function testPropertyNextPaymentDateTo()
    {
    }

    /**
     * Test attribute "desiredDiscountRateMin"
     */
    public function testPropertyDesiredDiscountRateMin()
    {
    }

    /**
     * Test attribute "desiredDiscountRateMax"
     */
    public function testPropertyDesiredDiscountRateMax()
    {
    }

    /**
     * Test attribute "xirrMin"
     */
    public function testPropertyXirrMin()
    {
    }

    /**
     * Test attribute "xirrMax"
     */
    public function testPropertyXirrMax()
    {
    }

    /**
     * Test attribute "pageSize"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "pageNr"
     */
    public function testPropertyPageNr()
    {
    }
}
