<?php
/**
 * SecondMarketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bondora API V1
 *
 * Bondora API version 1
 *
 * The version of the OpenAPI document: v1
 * Contact: investor@bondora.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace CedricZiel\OpenAPI\BondoraPHP;

use \CedricZiel\OpenAPI\BondoraPHP\Configuration;
use \CedricZiel\OpenAPI\BondoraPHP\ApiException;
use \CedricZiel\OpenAPI\BondoraPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SecondMarketApiTest Class Doc Comment
 *
 * @category Class
 * @package  CedricZiel\OpenAPI\BondoraPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SecondMarketApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for secondMarketBuy
     *
     * Buy loans from secondary market..
     *
     */
    public function testSecondMarketBuy()
    {
    }

    /**
     * Test case for secondMarketCancel
     *
     * Remove your loans from secondary market..
     *
     */
    public function testSecondMarketCancel()
    {
    }

    /**
     * Test case for secondMarketCancelMultiple
     *
     * Remove your loans from secondary market..
     *
     */
    public function testSecondMarketCancelMultiple()
    {
    }

    /**
     * Test case for secondMarketGet
     *
     * Gets LoanPartDetails info by identifier.
     *
     */
    public function testSecondMarketGet()
    {
    }

    /**
     * Test case for secondMarketGetActive
     *
     * Gets list of active secondary market items.
     *
     */
    public function testSecondMarketGetActive()
    {
    }

    /**
     * Test case for secondMarketGetItem
     *
     * Get the secondary market item summary.
     *
     */
    public function testSecondMarketGetItem()
    {
    }

    /**
     * Test case for secondMarketGetItemList
     *
     * Get the secondary market item summaries in a list.
     *
     */
    public function testSecondMarketGetItemList()
    {
    }

    /**
     * Test case for secondMarketGetItemList_0
     *
     * Get the secondary market item summaries in a list.
     *
     */
    public function testSecondMarketGetItemList0()
    {
    }

    /**
     * Test case for secondMarketGetList
     *
     * Gets LoanPartDetails info by identifiers in a list (up to 1000 items)..
     *
     */
    public function testSecondMarketGetList()
    {
    }

    /**
     * Test case for secondMarketGetList_0
     *
     * Gets LoanPartDetails info by identifiers in a list (up to 1000 items)..
     *
     */
    public function testSecondMarketGetList0()
    {
    }

    /**
     * Test case for secondMarketSell
     *
     * Sell your loans to secondary market..
     *
     */
    public function testSecondMarketSell()
    {
    }
}
